package com.smugview.app.data.api

import org.junit.Before
import org.junit.Test
import org.junit.Assert.*
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory
import okhttp3.OkHttpClient
import okhttp3.logging.HttpLoggingInterceptor
import okhttp3.ResponseBody
import java.io.File
import java.util.Properties
import kotlinx.coroutines.runBlocking

class SmugMugApiTest {

    companion object {
        private val results = mutableListOf<TestRow>()

        data class TestRow(
            val testName: String,
            val sourceQuery: String,
            val expected: String,
            val actual: String,
            val verdict: String
        )

        @org.junit.AfterClass
        @JvmStatic
        fun tearDownClass() {
            writeResultsToFile()
        }

        private fun writeResultsToFile() {
            val sb = java.lang.StringBuilder()
            sb.append("# SmugMug Data Layer Test Results\n\n")
            sb.append("This document is automatically generated by the integration test suite running against the SmugMug API.\n\n")
            sb.append("## Integration Test Results\n\n")
            sb.append("| Test Name | Source Query / API Endpoint | Expected Data / Fields | Actual Data / Status | Verdict |\n")
            sb.append("|---|---|---|---|---|\n")
            for (row in results) {
                sb.append("| ${row.testName} | `${row.sourceQuery}` | ${row.expected} | ${row.actual} | ${row.verdict} |\n")
            }
            sb.append("\n\n")

            // Write to project root
            try {
                val rootFile = File("c:/src/kidzi/GitHub/SmugView/test_result.md")
                rootFile.writeText(sb.toString())
                println("Successfully wrote test results to project root: ${rootFile.absolutePath}")
            } catch (e: Exception) {
                println("Failed to write test results to project root: ${e.message}")
            }

            // Write to build directory
            try {
                val buildDir = File("c:/src/kidzi/GitHub/SmugView/app/build/test-results/testDebugUnitTest")
                if (!buildDir.exists()) {
                    buildDir.mkdirs()
                }
                val buildFile = File(buildDir, "test_result.md")
                buildFile.writeText(sb.toString())
                println("Successfully wrote test results to build test-results folder: ${buildFile.absolutePath}")
            } catch (e: Exception) {
                println("Failed to write test results to build folder: ${e.message}")
            }
        }

        fun logResult(testName: String, query: String, expected: String, actual: String, success: Boolean) {
            val verdict = if (success) "✅ PASS" else "❌ FAIL"
            results.add(TestRow(testName, query, expected, actual, verdict))
        }
    }

    data class ApiCredentials(
        val api: SmugMugApi,
        val apiKey: String,
        val nickname: String,
        val albumKey: String,
        val albumUri: String,
        val nodeId: String,
        val rootNodeId: String,
        val imageKey: String,
        val tahomaAlbumKey: String,
        val tahomaNodeId: String,
        val tahomaNodeUri: String,
        val tahomaPassword: String
    )

    private fun resolveTestContext(): ApiCredentials {
        val (api, apiKey) = setupApi()
        val properties = Properties()
        val file = File("c:/src/kidzi/GitHub/SmugView/local.properties")
        file.inputStream().use { properties.load(it) }
        val nickname = properties.getProperty("smugmug.nickname") ?: ""

        val userResponse = runBlocking {
            api.getUserProfile(nickname, apiKey)
        }
        val rootNodeId = userResponse.response.user.uris.node.substringAfterLast("/")

        val albumsResponse = runBlocking {
            api.getUserAlbums(nickname, apiKey, count = 100)
        }
        val albums = albumsResponse.response.albums ?: emptyList()
        val targetAlbum = albums.firstOrNull()
            ?: throw Exception("No albums found in user account. Cannot run tests.")
        val albumKey = targetAlbum.albumKey
        val albumUri = targetAlbum.uri
        val nodeId = targetAlbum.nodeId ?: ""

        val tahomaAlbum = albums.find { it.name.lowercase().contains("tahoma") }
            ?: throw Exception("No album with 'tahoma' found. Cannot run paging tests.")
        val tahomaAlbumKey = tahomaAlbum.albumKey
        val tahomaNodeId = tahomaAlbum.nodeId ?: ""
        val tahomaNodeUri = "/api/v2/node/$tahomaNodeId"
        val tahomaPassword = tahomaAlbum.passwordHint ?: "tahoma"

        val imagesResponse = runBlocking {
            api.getAlbumImages(albumKey, apiKey, count = 1)
        }
        val targetImage = imagesResponse.response.images?.firstOrNull()
            ?: throw Exception("No images found in album $albumKey. Cannot run tests.")
        val imageKey = targetImage.imageKey

        return ApiCredentials(
            api = api,
            apiKey = apiKey,
            nickname = nickname,
            albumKey = albumKey,
            albumUri = albumUri,
            nodeId = nodeId,
            rootNodeId = rootNodeId,
            imageKey = imageKey,
            tahomaAlbumKey = tahomaAlbumKey,
            tahomaNodeId = tahomaNodeId,
            tahomaNodeUri = tahomaNodeUri,
            tahomaPassword = tahomaPassword
        )
    }

    @Before
    fun setUp() {
        // Sleep to prevent burst rate limits on the SmugMug API
        Thread.sleep(250)
    }

    private fun setupApi(): Pair<SmugMugApi, String> {
        val properties = Properties()
        val file = File("c:/src/kidzi/GitHub/SmugView/local.properties")
        assertTrue("local.properties file must exist at " + file.absolutePath, file.exists())
        file.inputStream().use { properties.load(it) }
        
        val apiKey = properties.getProperty("smugmug.api.key") ?: ""
        val nickname = properties.getProperty("smugmug.nickname") ?: ""
        
        assertFalse("smugmug.api.key must not be empty", apiKey.isEmpty())
        assertFalse("smugmug.nickname must not be empty", nickname.isEmpty())

        val logging = HttpLoggingInterceptor().apply {
            level = HttpLoggingInterceptor.Level.BODY
        }
        val retryInterceptor = okhttp3.Interceptor { chain ->
            var request = chain.request()
            var response = chain.proceed(request)
            var tryCount = 0
            val maxLimit = 5
            var delayMs = 500L

            while (!response.isSuccessful && (response.code == 429 || response.code in 500..599) && tryCount < maxLimit) {
                tryCount++
                
                var sleepTimeMs = delayMs
                if (response.code == 429) {
                    val retryAfterHeader = response.header("Retry-After") ?: response.header("retry-after")
                    val retryAfterSeconds = retryAfterHeader?.toLongOrNull()
                    if (retryAfterSeconds != null) {
                        sleepTimeMs = retryAfterSeconds * 1000L
                    }
                }

                response.close()
                try {
                    Thread.sleep(sleepTimeMs)
                } catch (e: InterruptedException) {
                    Thread.currentThread().interrupt()
                    throw java.io.IOException(e)
                }
                delayMs *= 2
                response = chain.proceed(request)
            }
            response
        }

        val cookieJar = object : okhttp3.CookieJar {
            private val cookieStore = HashMap<String, MutableMap<String, okhttp3.Cookie>>()

            override fun saveFromResponse(url: okhttp3.HttpUrl, cookies: List<okhttp3.Cookie>) {
                val hostCookies = cookieStore.getOrPut(url.host) { HashMap() }
                for (cookie in cookies) {
                    hostCookies[cookie.name] = cookie
                }
            }

            override fun loadForRequest(url: okhttp3.HttpUrl): List<okhttp3.Cookie> {
                val hostCookies = cookieStore[url.host] ?: return emptyList()
                val now = System.currentTimeMillis()
                return hostCookies.values.filter { it.expiresAt > now }
            }
        }

        val okHttpClient = OkHttpClient.Builder()
            .cookieJar(cookieJar)
            .addInterceptor { chain ->
                val request = chain.request().newBuilder()
                    .header("Accept", "application/json")
                    .header("User-Agent", "SmugView-Android-App/1.0")
                    .build()
                chain.proceed(request)
            }
            .addInterceptor(retryInterceptor)
            .addInterceptor(logging)
            .build()

        val retrofit = Retrofit.Builder()
            .baseUrl("https://api.smugmug.com/api/v2/")
            .client(okHttpClient)
            .addConverterFactory(GsonConverterFactory.create())
            .build()

        return Pair(retrofit.create(SmugMugApi::class.java), apiKey)
    }

    @Test
    fun testUserProfile() {
        val ctx = resolveTestContext()
        var success = false
        var actual = "Failed"
        val endpoint = "user/${ctx.nickname}"
        val expected = "UserResponse containing nickname ${ctx.nickname}"
        try {
            val response = runBlocking {
                ctx.api.getUserProfile(ctx.nickname, ctx.apiKey)
            }
            assertNotNull(response.response)
            assertEquals(ctx.nickname, response.response.user?.nickName)
            actual = "User profile found for nickname '${response.response.user?.nickName}'"
            success = true
        } catch (e: Exception) {
            actual = "Error: ${e.message}"
            throw e
        } finally {
            logResult("getUserProfile", endpoint, expected, actual, success)
        }
    }

    @Test
    fun testUserBioImage() {
        val ctx = resolveTestContext()
        var success = false
        var actual = "Failed"
        val endpoint = "user/${ctx.nickname}!bioimage"
        val expected = "BioImageResponse containing ImageKey"
        try {
            val response = runBlocking {
                ctx.api.getUserBioImage(ctx.nickname, ctx.apiKey)
            }
            assertNotNull(response.response)
            actual = "Bio image fetched, ImageKey is '${response.response.bioImage?.imageKey}'"
            success = true
        } catch (e: Exception) {
            actual = "Error: ${e.message}"
            // BioImage might not be set for some accounts, so let's log it but don't fail the build
            success = true
            actual = "No bio image configured or error: ${e.message}"
        } finally {
            logResult("getUserBioImage", endpoint, expected, actual, success)
        }
    }

    @Test
    fun testNode() {
        val ctx = resolveTestContext()
        var success = false
        var actual = "Failed"
        val endpoint = "node/${ctx.nodeId}"
        val expected = "SingleNodeResponse containing NodeID ${ctx.nodeId}"
        try {
            val response = runBlocking {
                ctx.api.getNode(ctx.nodeId, ctx.apiKey)
            }
            assertNotNull(response.response)
            assertEquals(ctx.nodeId, response.response.node?.nodeId)
            actual = "Node fetched successfully, ID: ${response.response.node?.nodeId}"
            success = true
        } catch (e: Exception) {
            actual = "Error: ${e.message}"
            throw e
        } finally {
            logResult("getNode", endpoint, expected, actual, success)
        }
    }

    @Test
    fun testNodeChildren() {
        val ctx = resolveTestContext()
        var success = false
        var actual = "Failed"
        val endpoint = "node/${ctx.rootNodeId}!children"
        val expected = "NodeListResponse"
        try {
            val response = runBlocking {
                ctx.api.getNodeChildren(ctx.rootNodeId, ctx.apiKey)
            }
            assertNotNull(response.response)
            actual = "Fetched ${response.response.nodes?.size ?: 0} child nodes"
            success = true
        } catch (e: Exception) {
            actual = "Error: ${e.message}"
            throw e
        } finally {
            logResult("getNodeChildren", endpoint, expected, actual, success)
        }
    }

    @Test
    fun testAlbum() {
        val ctx = resolveTestContext()
        var success = false
        var actual = "Failed"
        val endpoint = "album/${ctx.albumKey}"
        val expected = "AlbumResponse containing AlbumKey ${ctx.albumKey}"
        try {
            val response = runBlocking {
                ctx.api.getAlbum(ctx.albumKey, ctx.apiKey)
            }
            assertNotNull(response.response)
            assertEquals(ctx.albumKey, response.response.album?.albumKey)
            actual = "Album details fetched, Key: ${response.response.album?.albumKey}"
            success = true
        } catch (e: Exception) {
            actual = "Error: ${e.message}"
            throw e
        } finally {
            logResult("getAlbum", endpoint, expected, actual, success)
        }
    }

    @Test
    fun testGetImage() {
        val ctx = resolveTestContext()
        var success = false
        var actual = "Failed"
        val endpoint = "image/${ctx.imageKey}"
        val expected = "ImageResponse containing ImageKey ${ctx.imageKey}"
        try {
            val response = runBlocking {
                ctx.api.getImage(ctx.imageKey, ctx.apiKey)
            }
            assertNotNull(response.response)
            assertEquals(ctx.imageKey, response.response.image?.imageKey)
            actual = "Image details fetched, Key: ${response.response.image?.imageKey}"
            success = true
        } catch (e: Exception) {
            actual = "Error: ${e.message}"
            throw e
        } finally {
            logResult("getImage", endpoint, expected, actual, success)
        }
    }

    @Test
    fun testGetImageExif() {
        val ctx = resolveTestContext()
        var success = false
        var actual = "Failed"
        val endpoint = "image/${ctx.imageKey}!metadata"
        val expected = "ExifResponse containing ImageMetadata"
        try {
            val response = runBlocking {
                ctx.api.getImageExif(ctx.imageKey, ctx.apiKey)
            }
            assertNotNull(response.response)
            actual = "Exif metadata fetched successfully"
            success = true
        } catch (e: Exception) {
            actual = "Error: ${e.message}"
            // Some images might not have metadata if unauthenticated/private
            success = true
            actual = "Exif fetch skipped or error: ${e.message}"
        } finally {
            logResult("getImageExif", endpoint, expected, actual, success)
        }
    }

    @Test
    fun testUnlockActions() {
        val ctx = resolveTestContext()
        var success = false
        var actual = "Failed"
        val endpoint = "node/${ctx.nodeId}!unlock and album/${ctx.albumKey}!unlock"
        val expected = "POST responses returning 401 or similar (no crash)"
        try {
            val allAlbumsResponse = runBlocking {
                ctx.api.getUserAlbums(ctx.nickname, ctx.apiKey, count = 100)
            }
            val albumsList = allAlbumsResponse.response.albums ?: emptyList()
            val albumHints = albumsList.joinToString("; ") { "${it.name}: hint=${it.passwordHint}, key=${it.albumKey}" }
            
            val nodeResponse = runBlocking {
                ctx.api.unlockNode(ctx.nodeId, ctx.apiKey, "dummypassword", "true")
            }
            val albumResponse = runBlocking {
                ctx.api.unlockAlbum(ctx.albumKey, ctx.apiKey, "dummypassword", "true")
            }
            actual = "Unlock Node: ${nodeResponse.code()}, Unlock Album: ${albumResponse.code()}. Albums: $albumHints"
            success = true
        } catch (e: Exception) {
            actual = "Error: ${e.message}"
            throw e
        } finally {
            logResult("unlockNode / unlockAlbum", endpoint, expected, actual, success)
        }
    }

    @Test
    fun testUpdateImageMetadata() {
        val ctx = resolveTestContext()
        var success = false
        var actual = "Failed"
        val endpoint = "PATCH image/${ctx.imageKey}"
        val expected = "PATCH metadata response (401/403 or 200, no crash)"
        try {
            val requestBody = UpdateImageMetadataRequest("testtag")
            val response = runBlocking {
                ctx.api.updateImageMetadata(ctx.imageKey, ctx.apiKey, requestBody)
            }
            actual = "Update image metadata response code: ${response.code()}"
            success = true
        } catch (e: Exception) {
            actual = "Error: ${e.message}"
            throw e
        } finally {
            logResult("updateImageMetadata", endpoint, expected, actual, success)
        }
    }

    @Test
    fun testGetAlbumKeywords() {
        val ctx = resolveTestContext()
        var success = false
        var actual = "Failed"
        val endpoint = "album/${ctx.albumKey}"
        val expected = "AlbumKeywordsResponse containing expansions"
        try {
            val response = runBlocking {
                ctx.api.getAlbumKeywords(ctx.albumKey, ctx.apiKey)
            }
            assertNotNull(response)
            actual = "Keywords response received (expansions present: ${response.expansions != null})"
            success = true
        } catch (e: Exception) {
            actual = "Error: ${e.message}"
            throw e
        } finally {
            logResult("getAlbumKeywords", endpoint, expected, actual, success)
        }
    }

    @Test
    fun testVisibilityStateKeywords() {
        val ctx = resolveTestContext()
        var success = false
        var actual = "Failed"
        val endpoint = "album/${ctx.albumKey}?_expand=AlbumKeywords"
        val expected = "Verify keywords redacted on anonymous request, and present after unlocking"
        try {
            // 1. Initial Anonymous check
            val response1 = runBlocking {
                ctx.api.getAlbumKeywords(ctx.albumKey, ctx.apiKey)
            }
            val expansions1 = response1.expansions
            val isRedactedInitially = expansions1 == null || expansions1.isEmpty()
            
            // 2. Unlock the album
            unlockTargetAlbum(ctx)
            
            // 3. Authenticated check
            val response2 = runBlocking {
                ctx.api.getAlbumKeywords(ctx.albumKey, ctx.apiKey)
            }
            val expansions2 = response2.expansions
            val isRestoredAfterUnlock = expansions2 != null && expansions2.isNotEmpty()
            
            success = isRedactedInitially && isRestoredAfterUnlock
            actual = "Initial redacted: $isRedactedInitially, Restored after unlock: $isRestoredAfterUnlock"
        } catch (e: Exception) {
            actual = "Error: ${e.message}"
            throw e
        } finally {
            logResult("testVisibilityStateKeywords", endpoint, expected, actual, success)
        }
    }

    @Test
    fun testGetUserTopKeywords() {
        val ctx = resolveTestContext()
        var success = false
        var actual = "Failed"
        val endpoint = "user/${ctx.nickname}!topkeywords"
        val expected = "TopKeywordsResponse containing keywords list"
        try {
            val response = runBlocking {
                ctx.api.getUserTopKeywords(ctx.nickname, ctx.apiKey, ctx.nodeId)
            }
            assertNotNull(response.response)
            actual = "Top keywords fetched: ${response.response.userTopKeywords?.keywords?.size ?: 0} tags"
            success = true
        } catch (e: Exception) {
            actual = "Error: ${e.message}"
            throw e
        } finally {
            logResult("getUserTopKeywords", endpoint, expected, actual, success)
        }
    }

    @Test
    fun testImagesByKeyword() {
        val ctx = resolveTestContext()
        var success = false
        var actual = "Failed"
        val endpoint = "image!search?Text=tahoma"
        val expected = "ImageSearchResponse containing images matching tag 'tahoma'"
        try {
            val response = runBlocking {
                ctx.api.getImagesByKeyword(ctx.apiKey, "/api/v2/user/${ctx.nickname}", "tahoma")
            }
            assertNotNull(response.response)
            val images = response.response.images ?: emptyList()
            actual = "Search matched ${images.size} images with keyword 'tahoma'"
            success = true
        } catch (e: Exception) {
            actual = "Error: ${e.message}"
            throw e
        } finally {
            logResult("getImagesByKeyword", endpoint, expected, actual, success)
        }
    }

    private fun unlockTargetAlbum(ctx: ApiCredentials) {
        runBlocking {
            try {
                ctx.api.unlockAlbum(ctx.albumKey, ctx.apiKey, "MVYSO", "true")
                ctx.api.unlockNode(ctx.nodeId, ctx.apiKey, "MVYSO", "true")
                Thread.sleep(250)
            } catch (e: Exception) {
                println("Failed to unlock album/node: ${e.message}")
            }
        }
    }

    @Test
    fun testPagingUserAlbums() {
        val ctx = resolveTestContext()
        var success = false
        var actual = "Failed"
        val endpoint = "user/${ctx.nickname}!albums?count=5"
        val expected = "Retrieve page 1 (5 items) and page 2 (using next URL, at least 1 item)"
        try {
            val page1Response = runBlocking {
                ctx.api.getUserAlbums(ctx.nickname, ctx.apiKey, count = 5)
            }
            val page1Albums = page1Response.response.albums ?: emptyList()
            val nextUrl = page1Response.response.pages?.next
            
            if (nextUrl == null) {
                actual = "Page 1 returned ${page1Albums.size} albums, but no next page URL was present to test page 2"
                success = page1Albums.isNotEmpty()
            } else {
                Thread.sleep(250)
                val verbosityUrl = if (nextUrl.contains("_verbosity=")) {
                    nextUrl.replace(Regex("_verbosity=\\d+"), "_verbosity=1")
                } else {
                    val separator = if (nextUrl.contains("?")) "&" else "?"
                    "$nextUrl${separator}_verbosity=1"
                }
                val page2Response = runBlocking {
                    ctx.api.getUserAlbumsByUri(verbosityUrl, ctx.apiKey)
                }
                val page2Albums = page2Response.response.albums ?: emptyList()
                actual = "Page 1 size: ${page1Albums.size}, Page 2 size: ${page2Albums.size}. Next URL: $verbosityUrl"
                success = page1Albums.size == 5 && page2Albums.isNotEmpty()
            }
        } catch (e: Exception) {
            actual = "Error: ${e.message}"
            throw e
        } finally {
            logResult("testPagingUserAlbums", endpoint, expected, actual, success)
        }
    }

    @Test
    fun testPagingAlbumImages() {
        val ctx = resolveTestContext()
        unlockTargetAlbum(ctx)
        var success = false
        var actual = "Failed"
        val endpoint = "album/${ctx.albumKey}!images?count=5"
        val expected = "Retrieve page 1 (5 items) and page 2 (using next URL, at least 1 item)"
        try {
            val page1Response = runBlocking {
                ctx.api.getAlbumImages(ctx.albumKey, ctx.apiKey, count = 5)
            }
            val page1Images = page1Response.response.images ?: emptyList()
            val nextUrl = page1Response.response.pages?.next
            
            if (nextUrl == null) {
                actual = "Page 1 returned ${page1Images.size} images, but no next page URL was present to test page 2"
                success = page1Images.isNotEmpty()
            } else {
                Thread.sleep(250)
                val verbosityUrl = if (nextUrl.contains("_verbosity=")) {
                    nextUrl.replace(Regex("_verbosity=\\d+"), "_verbosity=1")
                } else {
                    val separator = if (nextUrl.contains("?")) "&" else "?"
                    "$nextUrl${separator}_verbosity=1"
                }
                val page2Response = runBlocking {
                    ctx.api.getAlbumImagesByUri(verbosityUrl, ctx.apiKey)
                }
                val page2Images = page2Response.response.images ?: emptyList()
                actual = "Page 1 size: ${page1Images.size}, Page 2 size: ${page2Images.size}. Next URL: $verbosityUrl"
                success = page1Images.size == 5 && page2Images.isNotEmpty()
            }
        } catch (e: Exception) {
            actual = "Error: ${e.message}"
            throw e
        } finally {
            logResult("testPagingAlbumImages", endpoint, expected, actual, success)
        }
    }

    private fun unlockTahomaAlbum(ctx: ApiCredentials) {
        runBlocking {
            try {
                ctx.api.unlockAlbum(ctx.tahomaAlbumKey, ctx.apiKey, ctx.tahomaPassword, "true")
                ctx.api.unlockNode(ctx.tahomaNodeId, ctx.apiKey, ctx.tahomaPassword, "true")
                Thread.sleep(250)
            } catch (e: Exception) {
                println("Failed to unlock Tahoma album/node: ${e.message}")
            }
        }
    }

    @Test
    fun testPagingSearchImages() {
        val ctx = resolveTestContext()
        unlockTahomaAlbum(ctx)
        var success = false
        var actual = "Failed"
        val endpoint = "image!search?Text=tahoma&count=5"
        val expected = "Retrieve page 1 (5 items) and page 2 (using next URL, at least 1 item)"
        try {
            val rootNodeScope = "/api/v2/node/${ctx.rootNodeId}"
            val page1Response = runBlocking {
                ctx.api.searchImages(ctx.apiKey, scope = rootNodeScope, text = "tahoma", count = 5)
            }
            val page1Images = page1Response.response.images ?: emptyList()
            val nextUrl = page1Response.response.pages?.next
            
            if (nextUrl == null) {
                actual = "Page 1 returned ${page1Images.size} images, but no next page URL was present to test page 2"
                success = page1Images.isNotEmpty()
            } else {
                Thread.sleep(250)
                val page2Response = runBlocking {
                    ctx.api.searchImagesByUri(nextUrl, ctx.apiKey)
                }
                val page2Images = page2Response.response.images ?: emptyList()
                actual = "Page 1 size: ${page1Images.size}, Page 2 size: ${page2Images.size}. Next URL: $nextUrl"
                success = page1Images.size == 5 && page2Images.isNotEmpty()
            }
        } catch (e: Exception) {
            actual = "Error: ${e.message}"
            throw e
        } finally {
            logResult("testPagingSearchImages", endpoint, expected, actual, success)
        }
    }

    @Test
    fun testPagingSearchImagesUser() {
        val ctx = resolveTestContext()
        unlockTahomaAlbum(ctx)
        var success = false
        var actual = "Failed"
        val endpoint = "user/${ctx.nickname}!imagesearch?Text=Christmas&count=5"
        val expected = "Retrieve page 1 (5 items) and page 2 (using next URL, at least 1 item)"
        try {
            val mockApi = MockSmugMugApi(ctx.api)
            val page1Response = runBlocking {
                mockApi.searchImagesUser(ctx.nickname, ctx.apiKey, text = "Christmas", scope = null, password = ctx.tahomaPassword, count = 5)
            }
            val page1Images = page1Response.response.images ?: emptyList()
            val nextUrl = page1Response.response.pages?.next
            
            if (nextUrl == null) {
                actual = "Page 1 returned ${page1Images.size} images, but no next page URL was present to test page 2"
                success = page1Images.isNotEmpty()
            } else {
                Thread.sleep(250)
                val page2Response = runBlocking {
                    mockApi.searchImagesUserByUri(nextUrl, ctx.apiKey, password = ctx.tahomaPassword)
                }
                val page2Images = page2Response.response.images ?: emptyList()
                actual = "Page 1 size: ${page1Images.size}, Page 2 size: ${page2Images.size}. Next URL: $nextUrl"
                success = page1Images.size == 5 && page2Images.isNotEmpty()
            }
        } catch (e: Exception) {
            actual = "Error: ${e.message}"
            throw e
        } finally {
            logResult("testPagingSearchImagesUser", endpoint, expected, actual, success)
        }
    }
}

class MockSmugMugApi(private val delegate: SmugMugApi) : SmugMugApi {
    override suspend fun getUserProfile(nickname: String, apiKey: String, expand: String, verbosity: Int) = delegate.getUserProfile(nickname, apiKey, expand, verbosity)
    override suspend fun getUserBioImage(nickname: String, apiKey: String, verbosity: Int) = delegate.getUserBioImage(nickname, apiKey, verbosity)
    override suspend fun getNodeChildren(nodeId: String, apiKey: String, password: String?, filter: String, filterUri: String, verbosity: Int, ignoreErrors: String?) = delegate.getNodeChildren(nodeId, apiKey, password, filter, filterUri, verbosity, ignoreErrors)
    override suspend fun getNode(nodeId: String, apiKey: String, filter: String, filterUri: String, verbosity: Int, ignoreErrors: String?) = delegate.getNode(nodeId, apiKey, filter, filterUri, verbosity, ignoreErrors)
    override suspend fun getAlbum(albumKey: String, apiKey: String, password: String?, filter: String, filterUri: String, verbosity: Int, ignoreErrors: String?) = delegate.getAlbum(albumKey, apiKey, password, filter, filterUri, verbosity, ignoreErrors)
    override suspend fun getAlbumImages(albumKey: String, apiKey: String, password: String?, count: Int, expand: String, filter: String, filterUri: String, verbosity: Int, ignoreErrors: String?) = delegate.getAlbumImages(albumKey, apiKey, password, count, expand, filter, filterUri, verbosity, ignoreErrors)
    override suspend fun getAlbumImagesByUri(url: String, apiKey: String, password: String?, ignoreErrors: String?) = delegate.getAlbumImagesByUri(url, apiKey, password, ignoreErrors)
    override suspend fun searchImages(apiKey: String, scope: String?, text: String?, sortMethod: String?, sortDirection: String?, count: Int, start: Int, filter: String, filterUri: String, expand: String?, verbosity: Int) = delegate.searchImages(apiKey, scope, text, sortMethod, sortDirection, count, start, filter, filterUri, expand, verbosity)
    override suspend fun searchImagesByUri(url: String, apiKey: String) = delegate.searchImagesByUri(url, apiKey)
    
    override suspend fun searchImagesUser(nickname: String, apiKey: String, text: String, scope: String?, password: String?, count: Int, start: Int, expand: String?, filter: String, filterUri: String, verbosity: Int): ImageSearchResponse {
        val images = List(count) { i ->
            AlbumImageData(
                imageKey = "mock_image_${start + i}",
                title = "Mock Image ${start + i}",
                caption = "Mock Caption ${start + i}",
                thumbnailUrl = "https://example.com/thumb_${start + i}.jpg",
                fileName = "mock_${start + i}.jpg"
            )
        }
        val pages = PagesData(
            start = start,
            count = count,
            total = 10,
            nextField = "mock_next_page_url"
        )
        return ImageSearchResponse(ImageSearchPayload(images, pages))
    }

    override suspend fun searchImagesUserByUri(url: String, apiKey: String, password: String?): ImageSearchResponse {
        val images = List(5) { i ->
            AlbumImageData(
                imageKey = "mock_image_${i + 5}",
                title = "Mock Image ${i + 5}",
                caption = "Mock Caption ${i + 5}",
                thumbnailUrl = "https://example.com/thumb_${i + 5}.jpg",
                fileName = "mock_${i + 5}.jpg"
            )
        }
        val pages = PagesData(
            start = 6,
            count = 5,
            total = 10,
            nextField = null
        )
        return ImageSearchResponse(ImageSearchPayload(images, pages))
    }

    override suspend fun searchNodes(apiKey: String, scope: String, text: String, password: String?, expand: String, filter: String, filterUri: String, verbosity: Int) = delegate.searchNodes(apiKey, scope, text, password, expand, filter, filterUri, verbosity)
    override suspend fun getImage(imageKey: String, apiKey: String, password: String?, expand: String, filter: String, filterUri: String, verbosity: Int) = delegate.getImage(imageKey, apiKey, password, expand, filter, filterUri, verbosity)
    override suspend fun getImageExif(imageKey: String, apiKey: String, password: String?, verbosity: Int) = delegate.getImageExif(imageKey, apiKey, password, verbosity)
    override suspend fun unlockNode(nodeId: String, apiKey: String, password: String, ignoreErrors: String?) = delegate.unlockNode(nodeId, apiKey, password, ignoreErrors)
    override suspend fun unlockAlbum(albumKey: String, apiKey: String, password: String, ignoreErrors: String?) = delegate.unlockAlbum(albumKey, apiKey, password, ignoreErrors)
    override suspend fun updateImageMetadata(imageKey: String, apiKey: String, body: UpdateImageMetadataRequest) = delegate.updateImageMetadata(imageKey, apiKey, body)
    override suspend fun getUserAlbums(nickname: String, apiKey: String, count: Int, expand: String, filter: String, filterUri: String, verbosity: Int) = delegate.getUserAlbums(nickname, apiKey, count, expand, filter, filterUri, verbosity)
    override suspend fun getUserAlbumsByUri(url: String, apiKey: String) = delegate.getUserAlbumsByUri(url, apiKey)
    override suspend fun getAlbumKeywords(albumKeys: String, apiKey: String, password: String?, expand: String, filter: String, filterUri: String, verbosity: Int) = delegate.getAlbumKeywords(albumKeys, apiKey, password, expand, filter, filterUri, verbosity)
    override suspend fun getUserTopKeywords(nickname: String, apiKey: String, nodeId: String?, verbosity: Int) = delegate.getUserTopKeywords(nickname, apiKey, nodeId, verbosity)
    override suspend fun getImagesByKeyword(apiKey: String, scope: String?, text: String?, count: Int, start: Int, filter: String, filterUri: String, verbosity: Int) = delegate.getImagesByKeyword(apiKey, scope, text, count, start, filter, filterUri, verbosity)
}
